CREATE TABLE IF NOT EXISTS bookings (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    flight_id BIGINT NOT NULL,
    passenger_count SMALLINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);